version: 2.1

jobs:
  run-python-files:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: |
            pip install -r requirements.txt

      - run:
          name: Run Python files
          command: |
            find . -name "*.py" -exec python {} \;

workflows:
  run-python-files-workflow:
    jobs:
      - run-python-files
