# _config.yml

# Theme configuration (if applicable)
# theme: my-theme (Replace "my-theme" with the name of the theme you are using)

# Custom styles
style: |
  body {
    background-color: white;
    color: black;
  }
