name: Pyre Action

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  pyre-analysis:
    name: Pyre Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pyre Action
        uses: facebook/pyre-action@v0.0.1
        continue-on-error: true
