name: Greetings

on:
  pull_request_target:
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Greet the User
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Hello, @{github.actor}! 👋 Thank you for creating your first issue in our repository. We appreciate your contribution!"
          pr-message: "Hello, @{github.actor}! 👋 Thank you for submitting your first pull request to our repository. We appreciate your contribution!"

