name: Python Indentation Check and Pull Request

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  indent_check_and_pr:
    name: Indentation Check and Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with the version of Python used in your repository

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8 for Indentation Errors
        run: |
          if flake8 --select=E --show-source --quiet .; then
            echo "No indentation errors found."
          else
            echo "Indentation errors found. Fixing the errors..."
            autopep8 --in-place --recursive .
          fi

      - name: Create and Push Fix Branch
        run: |
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
          else
            echo "Changes found. Creating a pull request with the changes..."
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git checkout -b fix-indentation-errors
            git commit -a -m "Fix Python indentation errors"
            git push origin fix-indentation-errors
          fi
