name: Check Code Lines

on:
  push:
    branches:
      - main  # Change 'main' to the name of your default branch

jobs:
  check_code_lines:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Count Python lines
        id: count_python_lines
        run: |
          python_lines=$(find . -name '*.py' | xargs cat | wc -l)
          echo "::set-output name=python_lines::$python_lines"

      - name: Count TXT lines
        id: count_txt_lines
        run: |
          txt_lines=$(find . -name '*.txt' | xargs cat | wc -l)
          echo "::set-output name=txt_lines::$txt_lines"

      - name: Count MD lines
        id: count_md_lines
        run: |
          md_lines=$(find . -name '*.md' | xargs cat | wc -l)
          echo "::set-output name=md_lines::$md_lines"

      - name: Count YAML lines
        id: count_yaml_lines
        run: |
          yaml_lines=$(find . -name '*.yml' | xargs cat | wc -l)
          echo "::set-output name=yaml_lines::$yaml_lines"

      - name: Display results
        run: |
          echo "Total lines of Python code: ${{ steps.count_python_lines.outputs.python_lines }}"
          echo "Total lines of TXT code: ${{ steps.count_txt_lines.outputs.txt_lines }}"
          echo "Total lines of MD code: ${{ steps.count_md_lines.outputs.md_lines }}"
          echo "Total lines of YAML code: ${{ steps.count_yaml_lines.outputs.yaml_lines }}"
