name: wemake-python-styleguide

on:
  pull_request:
    branches:
      - main  # Adjust this branch name if needed

jobs:
  styleguide:
    name: Check Python Styleguide
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: pip install -r requirements.txt  # Replace with the correct path to your requirements file if needed

      - name: Run wemake-python-styleguide
        uses: wemake-services/wemake-python-styleguide@0.18.0
