name: Lint Action

on:
  pull_request:
    branches:
      - main  # Adjust this branch name if needed

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Lint Code
        uses: wearerequired/lint-action@v2.3.0
