name: Run Python Files

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  run-python-files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python files
        run: |
          find . -name "*.py" -type f -exec python {} \;
