name: Python CI/CD

on:
  push:
    branches:
      - main

jobs:
  code-rating:
    name: Code Rating
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install flake8

    - name: Run Flake8
      run: flake8
      continue-on-error: true

  format-code:
    name: Format Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python and Pip
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Black
      run: pip install black

    - name: Run Black
      run: black . --exclude=venv || true

    - name: Configure Git
      run: |
        git config --global user.name "mrayanasim09"
        git config --global user.email "mrayanasim09@gmail.com"

    - name: Commit Changes
      run: |
        git add .
        git commit -m "Apply Black formatting" || echo "No changes to commit"

    - name: Push Changes
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin main
        echo $ACCESS_TOKEN | gh auth login --with-token
        gh pr create --title "Apply Black formatting" --body "This is an auto-generated pull request to apply Black formatting." --base main
