name: Python CI/CD

on:
  push:
    branches:
      - main

jobs:
  code-rating:
    name: Code Rating
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install flake8

    - name: Run Flake8
      run: flake8
      continue-on-error: true

  format-code:
    name: Format Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python and Pip
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Black
      run: pip install black

    - name: Run Black
      run: black . --exclude=venv || true

    - name: Ask for Manual Commit
      run: |
        echo "-------------------------------------------------------------"
        echo "Code formatting is complete. Please review the changes."
        echo "If you are satisfied with the changes, run the following commands to commit and push:"
        echo ""
        echo "git add ."
        echo "git commit -m 'Apply Black formatting'"
        echo "git push origin main"
        echo "-------------------------------------------------------------"

  create-pull-request:
    name: Create Pull Request
    needs: format-code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install GitHub CLI
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
        sudo add-apt-repository "deb [arch=amd64] https://cli.github.com/packages focal main"
        sudo apt update
        sudo apt install gh

    - name: Authenticate with GitHub CLI
      run: |
        echo "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" | gh auth login --with-token

    - name: Create Pull Request
      run: |
        echo "Do you want to create a pull request? (y/n)"
        read answer
        if [ "$answer" != "${answer#[Yy]}" ]; then
          gh pr create --title "Apply Black formatting" --body "This is an auto-generated pull request to apply Black formatting." --base main
        else
          echo "Pull request creation skipped."
        fi
