name: Python Code Error Check

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  check-errors:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run Python error checks
        run: |
          pytest --ignore=__pycache__ --ignore=venv
