name: Update Requirements

on:
  push:
    branches:
      - main  # Adjust this to the main branch name of your repository

jobs:
  update_requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Adjust this to the desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update requirements file
        run: |
          # Modify this script based on your specific requirements.txt format
          python update_requirements.py

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -am "Update requirements.txt" || true

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main  # Adjust this to the main branch name of your repository

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update requirements.txt"
          title: "Update requirements.txt"
          branch: "update-requirements"
          body: "This pull request updates the version of packages in requirements.txt."
